apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: welpedeserra/app:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/lanchonete?useTimezone=true&serverTimezone=America/Sao_Paulo
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"
          ports:
            - containerPort: 8080