apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app-namespace
  labels:
    app: tech-challenge
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080