apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app-namespace
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://lanchonete-database-1.c56iugywe6gv.us-east-1.rds.amazonaws.com:3306?useTimezone=true&serverTimezone=America/Sao_Paulo
  SPRING_DATASOURCE_USERNAME: admin
  environment: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app-namespace
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: bXlzZWN1cmVwYXNzd29yZA==